### ISSUE TITLE
Error routines:ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by rowild** [directus-community/agency-os#21]
On localhost, this app causes an error that seems to be related to missing SSL certificates. Here is what happens in my terminal on my MacBook's localhost beginning with `yarn install`:

```sh
directus-agency-tmpl-fe git:(main) ✗ yarn install
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
success Already up-to-date.

[6:11:47 AM] Nuxi 3.5.3
[6:11:47 AM] Nuxt 3.5.3 with Nitro 2.5.2

[6:13:46 AM] Nuxi 3.5.3
[6:13:46 AM] Nuxt 3.5.3 with Nitro 2.5.2
[6:13:46 AM] 
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.122.43:3000/
  > Network:  http://[2001:4bc9:1f98:5e35:ce5:720e:a6e9:bb58]:3000/
  > Network:  http://[2001:4bc9:1f98:5e35:f8e6:60c4:ff7d:26c9]:3000/

[6:13:46 AM] ◐ Loading Directus Module

Cannot start nuxt:  write EPROTO 009E0AF901000000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:355:

  at Transport.request (node_modules/@directus/sdk/dist/sdk.cjs.js:720:23)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Transport.get (node_modules/@directus/sdk/dist/sdk.cjs.js:734:16)
  at async ItemsHandler.readByQuery (node_modules/@directus/sdk/dist/sdk.cjs.js:64:32)
  at async setup (modules/directus-build.ts:29:33)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2140:18)
  at async installModule (node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:2407:95)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:2928:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:204:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:248:5)

 ERROR  [unhandledRejection] Cannot read properties of undefined (reading 'close')                                            6:15:17 AM

  at hardRestart (node_modules/nuxi/dist/chunks/dev.mjs:159:27)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Some posts related to this error:
https://stackoverflow.com/questions/54757867/how-to-fix-ssl-wrong-version-number-error-in-nuxtjs
https://github.com/axios/axios/issues/4840
https://stackoverflow.com/questions/60935596/error-ssl3-get-recordwrong-version-number-in-node-js-when-making-https-post-r

(Not sure, if they help. I personally do not know how to apply this fix in this template, since the issue seems to stem from the Directus SDK.)

**Comment by bryantgillespie** [comment]
Hmm....

If it's a Directus SDK issue - it's likely because the latest version of this repo uses an older version of the SDK. 

Scheduled for an upgrade in the coming weeks.

**Comment by rowild** [comment]
@bryantgillespie I found my ... incredibly! ... stupid error eventually! Instead of using `http://` for the Directus address in my env file, I typed `http.//` ... :-(  ... If I only could, I would Bite my a**! 

Sorry for troubling you!
